# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='wod',
            name='foot_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='wod',
            name='initial_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
