# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wods', '0002_auto_20160423_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='foot_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='initial_note',
            field=models.TextField(blank=True),
        ),
    ]
